### ISSUE TITLE
upgrade auf yform3 nicht möglich

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/poll#10]
https://github.com/FriendsOfREDAXO/poll/blob/aa081fc44e5a791fd31ec95f32dc9546c92c828e/package.yml#L17

**Comment by dergel** [comment]
ach shit .. das ziehst sich ja wirklich überall durch ;) ..

**Comment by omphteliba** [comment]
Kann man das nicht einfach durch `yform: '>2.2'` ersetzen?

**Comment by skerbis** [comment]
Ja.

**Comment by tyrant88** [comment]
Dann probier mal die neue Version 1.3.5

**Comment by skerbis** [comment]
@tyrant88 warst schneller. Danke. Release in Github nicht vergessen

**Comment by tyrant88** [comment]
ja, hatte vergessen wie man einen tag hinzufügt... aber das geht ja auch beim releasen auf github.
