### ISSUE TITLE
Bei E-Mails-Schutz wird output bei wiederholtem Versand nicht angepasst

### ISSUE THREAD

**Issue by 191977** [FriendsOfREDAXO/poll#15]
Hi,
wenn ich es richtig verstehe, sollte bei einem E-Mail-Voting beim absenden eine Fehlermeldung kommen, wenn mit dieser Mail schon einmal gevotet wurde. Die zweite Mail geht auch nicht raus und es wird auch kein neuer deaktivierter Eintrag erstellt. Jedoch erscheint trotzdem die Meldung 
"Wir haben eine E-Mail an die von dir angegebene Adresse gesendet. Bitte rufe den darin enthaltenen Link auf um deine Wahl zu bestätigen."
Wenn ich es richtig verstehe müsste das doch in der poll.php bei getOutput abgefangen werden?
Hier kann getestet werden wenn nötig, ist ein blankes redaxo, frischem poll-addon: [Deleted]

Vielen Dank schon mal und auch vielen Dank für das Addon!

**Comment by tyrant88** [comment]
Nein das ist privacy by design.

**Comment by 191977** [comment]
Ok, danke dir für die Info.
