### ISSUE TITLE
Fehler bei der Installation -> SQL Error: module_id ist NULL

### ISSUE THREAD

**Issue by greatif** [FriendsOfREDAXO/poll#17]
Bei der (Neu-)Installation von **Poll 1.4** (kein Update) auf REX 5.10.1 u. YForm 3.3.1 kommt es zur Fehlermeldung:

> AddOn poll konnte aus folgendem Grund nicht installiert werden:
> SQL error: Error while executing statement "insert into rex_module set name = :name, input = :input, output = :output, updatedate = :updatedate, updateuser = :updateuser where id = :module_id" using params {":name":"translate:poll_module",":input":"find();\n\n$select = new rex_select();\n$select->setName('REX_INPUT_VALUE[1]');\n\nforeach ($polls as $poll) {\n $select->addOption($poll->title, $poll->id);\n}\n\n$select->setSelected('REX_VALUE[1]');\n\necho $select->get();\n",":output":"setVar('poll', $poll);\n echo $fragment->parse('addons\/poll\/poll.php');\n}\n",":updatedate":"2020-05-26 14:57:48",":updateuser":"poll-addon",**_":module_id":null_**}! SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where id = NULL' at line 1

Siehe Screenshot:
![poll](https://user-images.githubusercontent.com/8527203/82902966-8aa57f00-9f60-11ea-85ec-e2da9f57bf2d.png)

Die **module_id** ist **NULL**.

**Comment by tyrant88** [comment]
Kann ich bestätigen.

**Comment by dergel** [comment]
ja da habe ich richtig MIst gebaut und übereilt rumgefummelt. weil ich Anpassungen brauchte.. Ich habe deswegen die Version rausgenommen und baue lokal an der Version 2.0 die einfach flexibler ist. Aber erst wenn das live auch alles geht werde ich die Änderungen deployen

**Comment by tyrant88** [comment]
Dann bin ich mal gespannt! Das mit dem zusätzlichem "comment" ist schon mal cool!

Die Umstellung auf sprog hatte ich bei mir lokal in den Projekten auch immer gemacht, es macht das AddOn aber erstmal unbenutzbar für Leute ohne sprog. Dafür ist mir auch noch keine richtig gute Lösung eingefallen.

Zwei Kleinigkeiten habe ich noch in einen PR ( https://github.com/FriendsOfREDAXO/poll/pull/18 ) - vielleicht magst du das noch einarbeiten, wenn du dazukommst.

**Comment by cedrus86** [comment]
> 
> 
> ja da habe ich richtig MIst gebaut und übereilt rumgefummelt. weil ich Anpassungen brauchte.. Ich habe deswegen die Version rausgenommen und baue lokal an der Version 2.0 die einfach flexibler ist. Aber erst wenn das live auch alles geht werde ich die Änderungen deployen

Heisst das, der Issue kann geschlossen werden?

**Comment by tyrant88** [comment]
Ja, das Issue kann geschlossen werden. Ich hatte gedacht wir führen noch eine Diskussion bzgl sprog.
