### ISSUE TITLE
Fehler bei der Installation

### ISSUE THREAD

**Issue by steri-rex** [FriendsOfREDAXO/poll#20]
Beim Versuch das Addon zu installieren kommt diese Fehlermeldung: (System: Redaxo 5.12.0 - Yform 3.4.1)
```
AddOn poll konnte aus folgendem Grund nicht installiert werden:
SQL error: Unable to fetch row.
```

**Comment by tyrant88** [comment]
Der Fehler wurde eigentlich schon in der Version 1.4 behoben...
@dergel Warum ist die Verison 1.4 denn offline?

**Comment by tyrant88** [comment]
Okay, 1.4 ist jetzt im installer

**Comment by schuer** [comment]
Ich wollte mich um den Dark Mode kümmern und kann das Problem bestätigen.

Fehler bei Installation von 1.4:

<img width="1256" alt="Screenshot 2021-11-13 at 12 06 50" src="https://user-images.githubusercontent.com/1297466/141631773-e111320d-4ba2-4195-94a7-e851da9190a4.png">

Fehler bei Installation von 1.3.5

<img width="1268" alt="Screenshot 2021-11-13 at 12 07 49" src="https://user-images.githubusercontent.com/1297466/141631899-43d1390c-7d26-4338-96b4-f1a57c7c94ac.png">

Anschließend hat eine erneute Installation von 1.4 funktioniert.

**Comment by tyrant88** [comment]
Der Fix war gar nicht im Release. Jetzt mit 1.4.2 sollte es keinen Fehler mehr geben.

**Comment by schuer** [comment]
Hat funktioniert, danke @tyrant88!

**Comment by tyrant88** [comment]
Ich denke das löst auch das ursprüngliche Problem, daher: close.
