### ISSUE TITLE
Fehlermeldung, wenn Modul auf Seite, Hilfe-Link falsch

### ISSUE THREAD

**Issue by abra100pro** [FriendsOfREDAXO/poll#24]
Der Hilfe-Link ist falsch, anstatt github.**com**/... steht dort github.**org**/...

Wenn ich das Umfragemodul auf einer Seite integriere, dann kommt diese Fehlermeldung:

Error while executing statement "SELECT `rex_poll_vote`.* FROM `rex_poll_vote` WHERE `option_id` = :p1 AND `status` = :p2 ORDER BY `rex_poll_vote`.`id` ASC" using params {"p1":1,"p2":1}! SQLSTATE[42S22]: Column not found: 1054 Unknown column 'status' in 'where clause'

Ich muss dazu sagen: Habe eine neue Redaxo-Version auf MAMP lokal installiert und diverseste Add-ons ausprobiert und zwischenzeitlich auch das System setup neu gestartet - es kann also sein, dass die Installation etwas zerschossen ist...

**Comment by alxndr-w** [comment]
@abra100pro tritt das Problem mit der aktuellen GitHub-Version immer noch auf? Hier wurde auch schon .org durch .com getauscht.
