### ISSUE TITLE
Beim Reinstallieren wird das Poll-Modul nicht geupdatet, sondern erneut angelegt.

### ISSUE THREAD

**Issue by greatif** [FriendsOfREDAXO/poll#8]
Beim Reinstallieren wird das Poll-Modul nicht geupdatet, sondern erneut angelegt.

Liegt wohl an **Zeile 29** der **install.php**:
`if ($module_id == rex_request('module_id', 'integer', -1)) {`

Wenn man diese z.B. ersetzt durch:
`if ($module_name == $yform_module_name) {`
funktioniert es.

**Comment by tyrant88** [comment]
Ich glaube es ist gar nicht gewünscht, dass ein vielleicht verändertes Modul hier überschrieben wird.
Der Mechanismus ist ja von YForm- da wird das Modul nur beim Drücken eines Buttons aktualisiert, wenn eben der URL-Parameter 'module_id' gesetzt ist.

**Comment by greatif** [comment]
Dass das von YForm kommt, habe ich gesehen. Aber wieso sollte das hier nicht gewünscht sein? Wenn - wie hier - ein Modul automatisch mit d. Addon installiert wird, dann macht es doch Sinn, für den Fall einer Reinstallation entweder zu prüfen, ob das Modul bereits vorhanden ist, oder aber dem Modul bei d. Installation gleich eine feste ID mitzugeben. Denn wenn das Modul mit `->getLastId()` installiert wird, dubliziert es sich sonst beim Reinstallieren.

Oder verstehe ich da einfach grundsätzlich was falsch?

**Comment by tyrant88** [comment]
Mir geht es darum, wenn ich das Modul verändert habe, ohne den Namen zu ändern, möchte ich es bei einem Update erstmal mit meinen Änderungen behalten.

**Comment by greatif** [comment]
Verstehe, das macht dann die automatische Installation grundsätzlich komplizierter, weil geprüft werden muss, ob Du was am Modul geändert hast.
Bevor `install.php` das Modul installiert, wird ja via
```
$searchtext = 'module:poll_basic_output';
$gm = rex_sql::factory();
$gm->setQuery('select * from rex_module where output LIKE "%' . $searchtext . '%"');
```
die Abfrage auf Module beschränkt, die im Output den Suchtext enthalten. Man kann in `$searchtext` ja eine Verions-Nummer aufnehmen. Wenn Du dann Änderungen am Modul vornimmst, änderst Du im Output auch die Versions-Nr., sodass dieses von der Abfrage ausgelassen wird.
Die nachfolgende Logik ändert man dann so, dass nur wenn kein solches Modul existiert UND auch sonst kein Modul dem Namen 'module:poll_basic_output', ein neues Modul installiert wird.

Alternative:
Man lässt die automatische Installation ganz weg.

Aber im Moment wird jedenfalls immer bei jeder Reinstallation ein neues Modul angelegt. So sollte es vllt. nicht bleiben...

**Comment by tyrant88** [comment]
Ich denke am sinnvollsten ist es eben wie bei YForm: das Modul wird nur bei Klick auf einen Button aktualisiert.
